### PR TITLE
update symfony version to v7

### PR DESCRIPTION
**Pull request by Rastusik**
Support for Symfony 7 like #8 but hopefully with fixed CI problems

### CODE REVIEW

**Comment by Rastusik** [comment]
I was a little proactive and it seems that with this PR, all the checks work: https://github.com/Rastusik/enqueue-bundle/pull/2

**Comment by betinvest** [comment]
@makasim could you merge this MR, please?

**Comment by makasim** [comment]
only if CI is green

**Comment by makasim** [comment]
symfony 5.x version could be removed

**Comment by betinvest** [comment]
> only if CI is green

it is green :)

**Comment by makasim** [comment]
Thanks for your pull request! We love contributions.

However, this repository is what we call a "subtree split": a read-only copy of one directory of the main enqueue-dev repository. It is used by Composer to allow developers to depend on specific Enqueue package.

If you want to contribute, you should instead open a pull request on the main repository:

https://github.com/php-enqueue/enqueue-dev

Read the contribution guide

https://github.com/php-enqueue/enqueue-dev/blob/master/docs/contribution.md

Thank you for your contribution!

**Pull request closed without merging**
